#!/bin/bash

EXTRAFLAGS="-DDUAL_BUFFERING -DUSE_PINNED_MEM -DGPUINDEX=${GPUINDEX} " EXTRASUFFIX="dualbuffer_pinned" make
make clean
EXTRAFLAGS="-DUSE_PINNED_MEM -DGPUINDEX=${GPUINDEX} " EXTRASUFFIX="pinned" make
make clean
EXTRAFLAGS=" -DGPUINDEX=${GPUINDEX} " EXTRASUFFIX="regular" make
make clean

